spring:
  application:
    name: apiRouterZuulGate
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ag_datashare?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
    cluster:
      - key: slave1 # slave1
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ag_sharelog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456

#解决http请求乱码的问题
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      URIEncoding: UTF-8
  redis:
     host: 127.0.0.1
     port: 6379
     timeout: 1000
    # Redis数据库索引（默认为0）
     database: 3
#  data:
#     mongodb:
#       uri: mongodb://ztgeo:123456@127.0.0.1:27017/http_db
server:
  port: 8001
zuul:
  ignored-patterns: /ztgeoNotice/**,/route/**
  SendErrorFilter:
    error:
      disable: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 50
customAttributes:
  ftpIp: 127.0.0.1 # ftp Ip
  ftpPort: 2121 # ftp端口号
  ftpUsername: bian # FTP登录账号
  ftpPassword: 123456 # FTP登录密码
  # 存储用户发送数据的数据库名
  #接口转发的数据库名
  httpName: "http_db"
yxtokenpath: http://192.168.1.251:1104/public/oauth/token
sqnankangkey: nankang
sqtoke:
  sqjdtokenurl: https://2.211.38.98:8343/v1/apigw/oauth2/token
  granttype: client_credentials
  client_id: 8947f32223bf4174bc7a014a96666ffc
  client_secret: 2805d50ef71246d3a394e078ba4a68fc
  scope: default
